---
title: ''
output: 
  pdf_document: 
    keep_tex: true
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(SeaSondeR)

CS_file_path <- system.file("data/CSS_TORA_24_04_04_0700.cs", package = "SeaSondeR")
APM_path <- system.file("data/MeasPattern.txt", package = "SeaSondeR")

```

```{r, message=FALSE}

seasonder_apm_obj <- seasonder_readSeaSondeRAPMFile(APM_path)

seasonder_apm_obj
```


```{r, message=FALSE}

seasonder_cs_obj <- seasonder_createSeaSondeRCS(CS_file_path, seasonder_apm_object = seasonder_apm_obj)


seasonder_cs_obj
```

Si el espectro incluye los límites de la región de primer orden, estos se leen y almacenan.

```{r spectra_plot_1, fig.cap="Espectro en la celda de rango 5. Las líneas verticales rojas indican las líneas de Bragg. Las regiones sombreadas en azul indican la región de primer orden leída del fichero de espectros. Las líneas gruesas horizontales indican la porción del espectro empleada para calcular el nivel de ruido."}

seasonder_SeaSondeRCS_plotSelfSpectrum(seasonder_cs_obj,antenna = 3, range_cell = 5, plot_FORs = T)

```

Si no cuenta con los límites de la región de primer orde o queremos recalcularlos, basta con definir los first order settings (o usar los valores por defecto) y calcularlos usando `seasonder_computeFORs`

```{r spectra_plot_2, message= FALSE, fig.cap="Espectro en la celda de rango 5 recalculado. Las líneas verticales rojas indican las líneas de Bragg. Las regiones sombreadas en azul indican la región de primer orden leída del fichero de espectros. Las líneas gruesas horizontales indican la porción del espectro empleada para calcular el nivel de ruido. La línea naranja muestra el espectro suavizado empleado para determinar los límites de la región de primer orden."}

first_order_settings <-   list(nsm = 2,
                    fdown = 10^(10/10),
                    flim = 10^(20/10),
                    noisefact = 10^(6/10),
                    currmax = 2,
                    reject_distant_bragg = TRUE, #  Default is to apply this test
                    reject_noise_ionospheric = F, #  Default is to apply this test (except for 42 MHz)

                    reject_noise_ionospheric_threshold = 0# Default is 0 dB threshold. Typically 0 dB should be used.
      )


seasonder_cs_obj <- seasonder_computeFORs(seasonder_cs_obj, FOR_control = first_order_settings)

seasonder_SeaSondeRCS_plotSelfSpectrum(seasonder_cs_obj,antenna = 3, range_cell = 5, plot_FORs = T)

```

```{r}

seasonder_cs_obj <-  seasonder_runMUSIC_in_FOR(seasonder_cs_obj, doppler_interpolation = 2L, options = list(PPMIN = 5, PWMAX = 50))

radial_metrics <- seasonder_exportRadialMetrics(seasonder_cs_obj)

head(radial_metrics)
```

```{r}
range_info <- seasonder_exportRangeInfo(seasonder_cs_obj)

head(range_info)
```

