%TableType: RNGI r001
%TableColumns: 12
%TableColumnTypes: SPRC RNGC NF01 NF02 NF03 ALM1 ALM2 ALM3 ALM4 NVSC NVDC NVAC 
%TableRows: 22
%TableStart: 
%% Range  RadDist  NoiseA1 NoiseA2 NoiseA3   FOL N1  FOL N2   FOL P1  FOL P2   Single  Dual    All   
%%  Cell    (km)    (dBm)   (dBm)   (dBm)    DopIndx DopIndx  DopIndx DopIndx Vectors Vectors Vectors
%    2    2.9926   -149.0   -148.5   -147.8      588      830     1202     1464      467       39      545
%    3    4.4889   -148.4   -147.0   -143.0      602      826     1214     1366      351       27      405
%    4    5.9852   -148.9   -147.8   -143.1      640      822     1228     1362      290       28      346
%    5    7.4815   -149.0   -148.9   -145.2      660      806     1242     1360      255       11      277
%    6    8.9778   -149.2   -148.9   -146.5      684      798     1252     1358      213        9      231
%    7   10.4740   -149.3   -148.7   -148.0      700      796     1258     1354      180       11      202
%    8   11.9703   -148.9   -148.7   -148.8      708      804     1260     1352      168       19      206
%    9   13.4666   -149.1   -149.3   -149.5      704      810     1258     1350      181        9      199
%   10   14.9629   -149.7   -149.7   -150.1      700      810     1258     1348      175       10      195
%   11   16.4592   -149.8   -149.0   -149.9      702      804     1262     1346      154        3      160
%   12   17.9555   -150.0   -149.1   -149.9      704      794     1264     1346      127        1      129
%   13   19.4518   -149.4   -148.4   -149.6      706      784     1268     1348      109        2      113
%   14   20.9481   -149.4   -148.8   -150.1      712      792     1272     1348      100        1      102
%   15   22.4444   -149.4   -148.4   -150.7      728      794     1278     1346       67        3       73
%   16   23.9407   -150.1   -148.5   -150.9      746      792     1282     1344       50        0       50
%   17   25.4370   -149.7   -148.6   -150.7      762      782     1282     1344       46        3       52
%   18   26.9333   -149.9   -149.2   -150.6      766      776     1282     1342       41        3       47
%   19   28.4296   -150.1   -149.1   -150.8      764      768     1288     1342       27        4       35
%   20   29.9258   -150.2   -149.0   -151.1      758      760     1292     1344       22        1       24
%   21   31.4221   -150.3   -149.3   -150.6      754      754     1294     1338       14        0       14
%   22   32.9184   -150.4   -149.0   -150.6      754      754     1294     1332        9        1       11
%   24   35.9110   -150.1   -149.3   -150.8      754      754     1296     1318        3        0        3
%TableEnd: 
