%TableType: RNGI r001
%TableColumns: 12
%TableColumnTypes: SPRC RNGC NF01 NF02 NF03 ALM1 ALM2 ALM3 ALM4 NVSC NVDC NVAC 
%TableRows: 22
%TableStart: 2
%% Range  RadDist  NoiseA1 NoiseA2 NoiseA3   FOL N1  FOL N2   FOL P1  FOL P2   Single  Dual    All   
%%  Cell    (km)    (dBm)   (dBm)   (dBm)    DopIndx DopIndx  DopIndx DopIndx Vectors Vectors Vectors
%    2    2.9926   -149.1   -148.3   -149.6      694      802     1242     1334      187       15      217
%    3    4.4889   -149.1   -147.1   -142.7      688      800     1242     1336      201        7      215
%    4    5.9852   -148.8   -147.5   -141.8      692      800     1250     1336      183       13      209
%    5    7.4815   -148.2   -147.7   -143.7      702      798     1264     1336      158       12      182
%    6    8.9778   -149.6   -148.3   -146.6      714      796     1272     1334      140        6      152
%    7   10.4740   -149.1   -148.1   -146.1      722      794     1278     1332      125        3      131
%    8   11.9703   -149.1   -148.8   -146.5      722      794     1278     1332      118        8      134
%    9   13.4666   -149.1   -148.2   -145.2      720      794     1278     1332      120        7      134
%   10   14.9629   -149.4   -148.4   -146.1      718      794     1276     1330      113        6      125
%   11   16.4592   -149.4   -148.5   -148.5      720      792     1278     1328      111        5      121
%   12   17.9555   -149.5   -149.1   -148.4      716      792     1278     1328      112        7      126
%   13   19.4518   -149.4   -149.7   -147.4      712      790     1278     1328       82       11      104
%   14   20.9481   -148.7   -148.7   -145.2      720      788     1280     1326       66        6       78
%   15   22.4444   -150.0   -148.7   -146.5      736      786     1282     1324       54        3       60
%   16   23.9407   -150.8   -148.7   -150.3      752      782     1282     1324       43        4       51
%   17   25.4370   -148.5   -148.6   -146.9      758      774     1282     1326       30        3       36
%   18   26.9333   -148.4   -148.5   -147.1      758      762     1282     1326       29        2       33
%   19   28.4296   -149.5   -148.8   -145.6      754      756     1280     1326       23        1       25
%   20   29.9258   -149.4   -148.8   -148.8      752      752     1284     1322       20        0       20
%   21   31.4221   -149.0   -149.1   -149.7      752      752     1286     1322       13        1       15
%   22   32.9184   -150.0   -150.0   -155.1      754      754     1290     1322        8        1       10
%   23   34.4147   -150.6   -149.9   -158.8      754      754     1290     1322        6        1        8
%TableEnd: 2
